// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Icon.proto

package wallet.core.jni.proto;

public final class Icon {
  private Icon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Icon.Proto.SigningInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Sender address.
     * </pre>
     *
     * <code>string from_address = 1;</code>
     */
    java.lang.String getFromAddress();
    /**
     * <pre>
     * Sender address.
     * </pre>
     *
     * <code>string from_address = 1;</code>
     */
    com.google.protobuf.ByteString
        getFromAddressBytes();

    /**
     * <pre>
     * Recipient address.
     * </pre>
     *
     * <code>string to_address = 2;</code>
     */
    java.lang.String getToAddress();
    /**
     * <pre>
     * Recipient address.
     * </pre>
     *
     * <code>string to_address = 2;</code>
     */
    com.google.protobuf.ByteString
        getToAddressBytes();

    /**
     * <pre>
     * Transfer amount.
     * </pre>
     *
     * <code>bytes value = 3;</code>
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <pre>
     * The amount of step to send with the transaction.
     * </pre>
     *
     * <code>bytes step_limit = 4;</code>
     */
    com.google.protobuf.ByteString getStepLimit();

    /**
     * <pre>
     * UNIX epoch time (from 1970.1.1 00:00:00) in microseconds
     * </pre>
     *
     * <code>int64 timestamp = 5;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     * Integer value increased by request to avoid replay attacks.
     * </pre>
     *
     * <code>bytes nonce = 6;</code>
     */
    com.google.protobuf.ByteString getNonce();

    /**
     * <pre>
     * Network identifier
     * </pre>
     *
     * <code>bytes network_id = 7;</code>
     */
    com.google.protobuf.ByteString getNetworkId();

    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 8;</code>
     */
    com.google.protobuf.ByteString getPrivateKey();
  }
  /**
   * <pre>
   * Input data necessary to create a signed transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Icon.Proto.SigningInput}
   */
  public  static final class SigningInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Icon.Proto.SigningInput)
      SigningInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningInput.newBuilder() to construct.
    private SigningInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningInput() {
      fromAddress_ = "";
      toAddress_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
      stepLimit_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      nonce_ = com.google.protobuf.ByteString.EMPTY;
      networkId_ = com.google.protobuf.ByteString.EMPTY;
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fromAddress_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              toAddress_ = s;
              break;
            }
            case 26: {

              value_ = input.readBytes();
              break;
            }
            case 34: {

              stepLimit_ = input.readBytes();
              break;
            }
            case 40: {

              timestamp_ = input.readInt64();
              break;
            }
            case 50: {

              nonce_ = input.readBytes();
              break;
            }
            case 58: {

              networkId_ = input.readBytes();
              break;
            }
            case 66: {

              privateKey_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Icon.internal_static_TW_Icon_Proto_SigningInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Icon.internal_static_TW_Icon_Proto_SigningInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Icon.SigningInput.class, wallet.core.jni.proto.Icon.SigningInput.Builder.class);
    }

    public static final int FROM_ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object fromAddress_;
    /**
     * <pre>
     * Sender address.
     * </pre>
     *
     * <code>string from_address = 1;</code>
     */
    public java.lang.String getFromAddress() {
      java.lang.Object ref = fromAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Sender address.
     * </pre>
     *
     * <code>string from_address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFromAddressBytes() {
      java.lang.Object ref = fromAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_ADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object toAddress_;
    /**
     * <pre>
     * Recipient address.
     * </pre>
     *
     * <code>string to_address = 2;</code>
     */
    public java.lang.String getToAddress() {
      java.lang.Object ref = toAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Recipient address.
     * </pre>
     *
     * <code>string to_address = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToAddressBytes() {
      java.lang.Object ref = toAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString value_;
    /**
     * <pre>
     * Transfer amount.
     * </pre>
     *
     * <code>bytes value = 3;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int STEP_LIMIT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString stepLimit_;
    /**
     * <pre>
     * The amount of step to send with the transaction.
     * </pre>
     *
     * <code>bytes step_limit = 4;</code>
     */
    public com.google.protobuf.ByteString getStepLimit() {
      return stepLimit_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    /**
     * <pre>
     * UNIX epoch time (from 1970.1.1 00:00:00) in microseconds
     * </pre>
     *
     * <code>int64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int NONCE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString nonce_;
    /**
     * <pre>
     * Integer value increased by request to avoid replay attacks.
     * </pre>
     *
     * <code>bytes nonce = 6;</code>
     */
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }

    public static final int NETWORK_ID_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString networkId_;
    /**
     * <pre>
     * Network identifier
     * </pre>
     *
     * <code>bytes network_id = 7;</code>
     */
    public com.google.protobuf.ByteString getNetworkId() {
      return networkId_;
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 8;</code>
     */
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFromAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fromAddress_);
      }
      if (!getToAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, toAddress_);
      }
      if (!value_.isEmpty()) {
        output.writeBytes(3, value_);
      }
      if (!stepLimit_.isEmpty()) {
        output.writeBytes(4, stepLimit_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(5, timestamp_);
      }
      if (!nonce_.isEmpty()) {
        output.writeBytes(6, nonce_);
      }
      if (!networkId_.isEmpty()) {
        output.writeBytes(7, networkId_);
      }
      if (!privateKey_.isEmpty()) {
        output.writeBytes(8, privateKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFromAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fromAddress_);
      }
      if (!getToAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, toAddress_);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, value_);
      }
      if (!stepLimit_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, stepLimit_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestamp_);
      }
      if (!nonce_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, nonce_);
      }
      if (!networkId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, networkId_);
      }
      if (!privateKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, privateKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Icon.SigningInput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Icon.SigningInput other = (wallet.core.jni.proto.Icon.SigningInput) obj;

      boolean result = true;
      result = result && getFromAddress()
          .equals(other.getFromAddress());
      result = result && getToAddress()
          .equals(other.getToAddress());
      result = result && getValue()
          .equals(other.getValue());
      result = result && getStepLimit()
          .equals(other.getStepLimit());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getNonce()
          .equals(other.getNonce());
      result = result && getNetworkId()
          .equals(other.getNetworkId());
      result = result && getPrivateKey()
          .equals(other.getPrivateKey());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getFromAddress().hashCode();
      hash = (37 * hash) + TO_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getToAddress().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + STEP_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getStepLimit().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + getNonce().hashCode();
      hash = (37 * hash) + NETWORK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getNetworkId().hashCode();
      hash = (37 * hash) + PRIVATE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Icon.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Icon.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Icon.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Icon.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Icon.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Icon.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Icon.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Icon.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Icon.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Icon.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Icon.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Icon.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Icon.SigningInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Input data necessary to create a signed transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Icon.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Icon.Proto.SigningInput)
        wallet.core.jni.proto.Icon.SigningInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Icon.internal_static_TW_Icon_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Icon.internal_static_TW_Icon_Proto_SigningInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Icon.SigningInput.class, wallet.core.jni.proto.Icon.SigningInput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Icon.SigningInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fromAddress_ = "";

        toAddress_ = "";

        value_ = com.google.protobuf.ByteString.EMPTY;

        stepLimit_ = com.google.protobuf.ByteString.EMPTY;

        timestamp_ = 0L;

        nonce_ = com.google.protobuf.ByteString.EMPTY;

        networkId_ = com.google.protobuf.ByteString.EMPTY;

        privateKey_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Icon.internal_static_TW_Icon_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Icon.SigningInput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Icon.SigningInput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Icon.SigningInput build() {
        wallet.core.jni.proto.Icon.SigningInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Icon.SigningInput buildPartial() {
        wallet.core.jni.proto.Icon.SigningInput result = new wallet.core.jni.proto.Icon.SigningInput(this);
        result.fromAddress_ = fromAddress_;
        result.toAddress_ = toAddress_;
        result.value_ = value_;
        result.stepLimit_ = stepLimit_;
        result.timestamp_ = timestamp_;
        result.nonce_ = nonce_;
        result.networkId_ = networkId_;
        result.privateKey_ = privateKey_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Icon.SigningInput) {
          return mergeFrom((wallet.core.jni.proto.Icon.SigningInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Icon.SigningInput other) {
        if (other == wallet.core.jni.proto.Icon.SigningInput.getDefaultInstance()) return this;
        if (!other.getFromAddress().isEmpty()) {
          fromAddress_ = other.fromAddress_;
          onChanged();
        }
        if (!other.getToAddress().isEmpty()) {
          toAddress_ = other.toAddress_;
          onChanged();
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        if (other.getStepLimit() != com.google.protobuf.ByteString.EMPTY) {
          setStepLimit(other.getStepLimit());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getNonce() != com.google.protobuf.ByteString.EMPTY) {
          setNonce(other.getNonce());
        }
        if (other.getNetworkId() != com.google.protobuf.ByteString.EMPTY) {
          setNetworkId(other.getNetworkId());
        }
        if (other.getPrivateKey() != com.google.protobuf.ByteString.EMPTY) {
          setPrivateKey(other.getPrivateKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Icon.SigningInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Icon.SigningInput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fromAddress_ = "";
      /**
       * <pre>
       * Sender address.
       * </pre>
       *
       * <code>string from_address = 1;</code>
       */
      public java.lang.String getFromAddress() {
        java.lang.Object ref = fromAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Sender address.
       * </pre>
       *
       * <code>string from_address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFromAddressBytes() {
        java.lang.Object ref = fromAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Sender address.
       * </pre>
       *
       * <code>string from_address = 1;</code>
       */
      public Builder setFromAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sender address.
       * </pre>
       *
       * <code>string from_address = 1;</code>
       */
      public Builder clearFromAddress() {
        
        fromAddress_ = getDefaultInstance().getFromAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sender address.
       * </pre>
       *
       * <code>string from_address = 1;</code>
       */
      public Builder setFromAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toAddress_ = "";
      /**
       * <pre>
       * Recipient address.
       * </pre>
       *
       * <code>string to_address = 2;</code>
       */
      public java.lang.String getToAddress() {
        java.lang.Object ref = toAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Recipient address.
       * </pre>
       *
       * <code>string to_address = 2;</code>
       */
      public com.google.protobuf.ByteString
          getToAddressBytes() {
        java.lang.Object ref = toAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Recipient address.
       * </pre>
       *
       * <code>string to_address = 2;</code>
       */
      public Builder setToAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Recipient address.
       * </pre>
       *
       * <code>string to_address = 2;</code>
       */
      public Builder clearToAddress() {
        
        toAddress_ = getDefaultInstance().getToAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Recipient address.
       * </pre>
       *
       * <code>string to_address = 2;</code>
       */
      public Builder setToAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toAddress_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Transfer amount.
       * </pre>
       *
       * <code>bytes value = 3;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <pre>
       * Transfer amount.
       * </pre>
       *
       * <code>bytes value = 3;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Transfer amount.
       * </pre>
       *
       * <code>bytes value = 3;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString stepLimit_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The amount of step to send with the transaction.
       * </pre>
       *
       * <code>bytes step_limit = 4;</code>
       */
      public com.google.protobuf.ByteString getStepLimit() {
        return stepLimit_;
      }
      /**
       * <pre>
       * The amount of step to send with the transaction.
       * </pre>
       *
       * <code>bytes step_limit = 4;</code>
       */
      public Builder setStepLimit(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stepLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The amount of step to send with the transaction.
       * </pre>
       *
       * <code>bytes step_limit = 4;</code>
       */
      public Builder clearStepLimit() {
        
        stepLimit_ = getDefaultInstance().getStepLimit();
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * UNIX epoch time (from 1970.1.1 00:00:00) in microseconds
       * </pre>
       *
       * <code>int64 timestamp = 5;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * UNIX epoch time (from 1970.1.1 00:00:00) in microseconds
       * </pre>
       *
       * <code>int64 timestamp = 5;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * UNIX epoch time (from 1970.1.1 00:00:00) in microseconds
       * </pre>
       *
       * <code>int64 timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString nonce_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Integer value increased by request to avoid replay attacks.
       * </pre>
       *
       * <code>bytes nonce = 6;</code>
       */
      public com.google.protobuf.ByteString getNonce() {
        return nonce_;
      }
      /**
       * <pre>
       * Integer value increased by request to avoid replay attacks.
       * </pre>
       *
       * <code>bytes nonce = 6;</code>
       */
      public Builder setNonce(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Integer value increased by request to avoid replay attacks.
       * </pre>
       *
       * <code>bytes nonce = 6;</code>
       */
      public Builder clearNonce() {
        
        nonce_ = getDefaultInstance().getNonce();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString networkId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Network identifier
       * </pre>
       *
       * <code>bytes network_id = 7;</code>
       */
      public com.google.protobuf.ByteString getNetworkId() {
        return networkId_;
      }
      /**
       * <pre>
       * Network identifier
       * </pre>
       *
       * <code>bytes network_id = 7;</code>
       */
      public Builder setNetworkId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        networkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Network identifier
       * </pre>
       *
       * <code>bytes network_id = 7;</code>
       */
      public Builder clearNetworkId() {
        
        networkId_ = getDefaultInstance().getNetworkId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 8;</code>
       */
      public com.google.protobuf.ByteString getPrivateKey() {
        return privateKey_;
      }
      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 8;</code>
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 8;</code>
       */
      public Builder clearPrivateKey() {
        
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Icon.Proto.SigningInput)
    }

    // @@protoc_insertion_point(class_scope:TW.Icon.Proto.SigningInput)
    private static final wallet.core.jni.proto.Icon.SigningInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Icon.SigningInput();
    }

    public static wallet.core.jni.proto.Icon.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningInput>
        PARSER = new com.google.protobuf.AbstractParser<SigningInput>() {
      @java.lang.Override
      public SigningInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningInput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Icon.SigningInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Icon.Proto.SigningOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Encoded transaction (signature pre-image).
     * </pre>
     *
     * <code>string encoded = 1;</code>
     */
    java.lang.String getEncoded();
    /**
     * <pre>
     * Encoded transaction (signature pre-image).
     * </pre>
     *
     * <code>string encoded = 1;</code>
     */
    com.google.protobuf.ByteString
        getEncodedBytes();

    /**
     * <pre>
     * Signature.
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * <pre>
   * Transaction signing output.
   * </pre>
   *
   * Protobuf type {@code TW.Icon.Proto.SigningOutput}
   */
  public  static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Icon.Proto.SigningOutput)
      SigningOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningOutput.newBuilder() to construct.
    private SigningOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningOutput() {
      encoded_ = "";
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              encoded_ = s;
              break;
            }
            case 18: {

              signature_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Icon.internal_static_TW_Icon_Proto_SigningOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Icon.internal_static_TW_Icon_Proto_SigningOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Icon.SigningOutput.class, wallet.core.jni.proto.Icon.SigningOutput.Builder.class);
    }

    public static final int ENCODED_FIELD_NUMBER = 1;
    private volatile java.lang.Object encoded_;
    /**
     * <pre>
     * Encoded transaction (signature pre-image).
     * </pre>
     *
     * <code>string encoded = 1;</code>
     */
    public java.lang.String getEncoded() {
      java.lang.Object ref = encoded_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        encoded_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Encoded transaction (signature pre-image).
     * </pre>
     *
     * <code>string encoded = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEncodedBytes() {
      java.lang.Object ref = encoded_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encoded_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <pre>
     * Signature.
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEncodedBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, encoded_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(2, signature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEncodedBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, encoded_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Icon.SigningOutput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Icon.SigningOutput other = (wallet.core.jni.proto.Icon.SigningOutput) obj;

      boolean result = true;
      result = result && getEncoded()
          .equals(other.getEncoded());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENCODED_FIELD_NUMBER;
      hash = (53 * hash) + getEncoded().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Icon.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Icon.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Icon.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Icon.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Icon.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Icon.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Icon.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Icon.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Icon.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Icon.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Icon.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Icon.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Icon.SigningOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Transaction signing output.
     * </pre>
     *
     * Protobuf type {@code TW.Icon.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Icon.Proto.SigningOutput)
        wallet.core.jni.proto.Icon.SigningOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Icon.internal_static_TW_Icon_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Icon.internal_static_TW_Icon_Proto_SigningOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Icon.SigningOutput.class, wallet.core.jni.proto.Icon.SigningOutput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Icon.SigningOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        encoded_ = "";

        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Icon.internal_static_TW_Icon_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Icon.SigningOutput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Icon.SigningOutput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Icon.SigningOutput build() {
        wallet.core.jni.proto.Icon.SigningOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Icon.SigningOutput buildPartial() {
        wallet.core.jni.proto.Icon.SigningOutput result = new wallet.core.jni.proto.Icon.SigningOutput(this);
        result.encoded_ = encoded_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Icon.SigningOutput) {
          return mergeFrom((wallet.core.jni.proto.Icon.SigningOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Icon.SigningOutput other) {
        if (other == wallet.core.jni.proto.Icon.SigningOutput.getDefaultInstance()) return this;
        if (!other.getEncoded().isEmpty()) {
          encoded_ = other.encoded_;
          onChanged();
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Icon.SigningOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Icon.SigningOutput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object encoded_ = "";
      /**
       * <pre>
       * Encoded transaction (signature pre-image).
       * </pre>
       *
       * <code>string encoded = 1;</code>
       */
      public java.lang.String getEncoded() {
        java.lang.Object ref = encoded_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          encoded_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Encoded transaction (signature pre-image).
       * </pre>
       *
       * <code>string encoded = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEncodedBytes() {
        java.lang.Object ref = encoded_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          encoded_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Encoded transaction (signature pre-image).
       * </pre>
       *
       * <code>string encoded = 1;</code>
       */
      public Builder setEncoded(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encoded_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Encoded transaction (signature pre-image).
       * </pre>
       *
       * <code>string encoded = 1;</code>
       */
      public Builder clearEncoded() {
        
        encoded_ = getDefaultInstance().getEncoded();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Encoded transaction (signature pre-image).
       * </pre>
       *
       * <code>string encoded = 1;</code>
       */
      public Builder setEncodedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        encoded_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Signature.
       * </pre>
       *
       * <code>bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <pre>
       * Signature.
       * </pre>
       *
       * <code>bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Signature.
       * </pre>
       *
       * <code>bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Icon.Proto.SigningOutput)
    }

    // @@protoc_insertion_point(class_scope:TW.Icon.Proto.SigningOutput)
    private static final wallet.core.jni.proto.Icon.SigningOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Icon.SigningOutput();
    }

    public static wallet.core.jni.proto.Icon.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningOutput>
        PARSER = new com.google.protobuf.AbstractParser<SigningOutput>() {
      @java.lang.Override
      public SigningOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningOutput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningOutput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Icon.SigningOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Icon_Proto_SigningInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Icon_Proto_SigningInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Icon_Proto_SigningOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Icon_Proto_SigningOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nIcon.proto\022\rTW.Icon.Proto\"\246\001\n\014SigningI" +
      "nput\022\024\n\014from_address\030\001 \001(\t\022\022\n\nto_address" +
      "\030\002 \001(\t\022\r\n\005value\030\003 \001(\014\022\022\n\nstep_limit\030\004 \001(" +
      "\014\022\021\n\ttimestamp\030\005 \001(\003\022\r\n\005nonce\030\006 \001(\014\022\022\n\nn" +
      "etwork_id\030\007 \001(\014\022\023\n\013private_key\030\010 \001(\014\"3\n\r" +
      "SigningOutput\022\017\n\007encoded\030\001 \001(\t\022\021\n\tsignat" +
      "ure\030\002 \001(\014B\027\n\025wallet.core.jni.protob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TW_Icon_Proto_SigningInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TW_Icon_Proto_SigningInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Icon_Proto_SigningInput_descriptor,
        new java.lang.String[] { "FromAddress", "ToAddress", "Value", "StepLimit", "Timestamp", "Nonce", "NetworkId", "PrivateKey", });
    internal_static_TW_Icon_Proto_SigningOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TW_Icon_Proto_SigningOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Icon_Proto_SigningOutput_descriptor,
        new java.lang.String[] { "Encoded", "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
