platform :ios, '11.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
inhibit_all_warnings!
target 'TrustWalletCore' do
  use_frameworks!

  pod 'SwiftProtobuf'
  pod 'SwiftLint'

  target 'TrustWalletCoreTests'
end

post_install do |installer|
  # Set default deployment target
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
  end
end
