name: TrustWalletCore
options:
  bundleIdPrefix: com.trustwallet
  createIntermediateGroups: true
settings:
  base:
    HEADER_SEARCH_PATHS: $(SRCROOT)/wallet-core
    SYSTEM_HEADER_SEARCH_PATHS: ${SRCROOT}/include ${SRCROOT}/../build/local/include $(SRCROOT)/protobuf /usr/local/include /opt/homebrew/include
    CLANG_CXX_LANGUAGE_STANDARD: c++20
    SWIFT_VERSION: 5.1
    IPHONEOS_DEPLOYMENT_TARGET: 13.0
  configs:
    release:
      SWIFT_OPTIMIZATION_LEVEL: -Owholemodule
      SWIFT_COMPILATION_MODE: wholemodule
targets:
  WalletCore:
    type: framework
    platform: iOS
    sources:
      - path: include
        headerVisibility: public
        excludes:
          - "TrustWalletCore/TW*Proto.h"
      - path: wallet-core
        headerVisibility: project
        excludes:
          - ".vscode"
          - "proto/*.proto"
          - "Tron/Protobuf/*.proto"
          - "Zilliqa/Protobuf/*.proto"
          - "Cosmos/Protobuf/*.proto"
          - "Hedera/Protobuf/*.proto"
      - Sources
    dependencies:
      - target: protobuf
        link: true
      - sdk: libc++.tbd
      - framework: WalletCoreRs.xcframework
    scheme:
      testTargets:
        - WalletCoreTests
      gatherCoverageData: true
    settings:
      SKIP_INSTALL: false
      SUPPORTS_MACCATALYST: true
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      BUILD_LIBRARY_FOR_DISTRIBUTION: true
      INFOPLIST_FILE: 'Info.plist'
      CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION: YES_ERROR
      CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: $(inherited) false
      OTHER_CFLAGS: $(inherited) -Wno-comma -DNDEBUG
    postCompileScripts:
      - script: |
          export PATH=/opt/homebrew/bin:$PATH; 
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: SwiftLint
        shell: /bin/bash
        basedOnDependencyAnalysis: false

  WalletCoreTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    dependencies:
      - target: WalletCore
      - sdk: libc++.tbd

  protobuf:
    type: library.static
    platform: iOS
    sources:
      - protobuf/google/protobuf/any.cc
      - protobuf/google/protobuf/any.pb.cc
      - protobuf/google/protobuf/any_lite.cc
      - protobuf/google/protobuf/api.pb.cc
      - protobuf/google/protobuf/arena.cc
      - protobuf/google/protobuf/arenastring.cc
      - protobuf/google/protobuf/arenaz_sampler.cc
      - protobuf/google/protobuf/compiler/importer.cc
      - protobuf/google/protobuf/compiler/parser.cc
      - protobuf/google/protobuf/descriptor.cc
      - protobuf/google/protobuf/descriptor.pb.cc
      - protobuf/google/protobuf/descriptor_database.cc
      - protobuf/google/protobuf/duration.pb.cc
      - protobuf/google/protobuf/dynamic_message.cc
      - protobuf/google/protobuf/empty.pb.cc
      - protobuf/google/protobuf/extension_set.cc
      - protobuf/google/protobuf/extension_set_heavy.cc
      - protobuf/google/protobuf/field_mask.pb.cc
      - protobuf/google/protobuf/generated_enum_util.cc
      - protobuf/google/protobuf/generated_message_bases.cc
      - protobuf/google/protobuf/generated_message_reflection.cc
      - protobuf/google/protobuf/generated_message_tctable_full.cc
      - protobuf/google/protobuf/generated_message_tctable_lite.cc
      - protobuf/google/protobuf/generated_message_util.cc
      - protobuf/google/protobuf/implicit_weak_message.cc
      - protobuf/google/protobuf/inlined_string_field.cc
      - protobuf/google/protobuf/io/coded_stream.cc
      - protobuf/google/protobuf/io/gzip_stream.cc
      - protobuf/google/protobuf/io/io_win32.cc
      - protobuf/google/protobuf/io/printer.cc
      - protobuf/google/protobuf/io/strtod.cc
      - protobuf/google/protobuf/io/tokenizer.cc
      - protobuf/google/protobuf/io/zero_copy_stream.cc
      - protobuf/google/protobuf/io/zero_copy_stream_impl.cc
      - protobuf/google/protobuf/io/zero_copy_stream_impl_lite.cc
      - protobuf/google/protobuf/map.cc
      - protobuf/google/protobuf/map_field.cc
      - protobuf/google/protobuf/message.cc
      - protobuf/google/protobuf/message_lite.cc
      - protobuf/google/protobuf/parse_context.cc
      - protobuf/google/protobuf/reflection_ops.cc
      - protobuf/google/protobuf/repeated_field.cc
      - protobuf/google/protobuf/repeated_ptr_field.cc
      - protobuf/google/protobuf/service.cc
      - protobuf/google/protobuf/source_context.pb.cc
      - protobuf/google/protobuf/struct.pb.cc
      - protobuf/google/protobuf/stubs/bytestream.cc
      - protobuf/google/protobuf/stubs/common.cc
      - protobuf/google/protobuf/stubs/int128.cc
      - protobuf/google/protobuf/stubs/status.cc
      - protobuf/google/protobuf/stubs/statusor.cc
      - protobuf/google/protobuf/stubs/stringpiece.cc
      - protobuf/google/protobuf/stubs/stringprintf.cc
      - protobuf/google/protobuf/stubs/structurally_valid.cc
      - protobuf/google/protobuf/stubs/strutil.cc
      - protobuf/google/protobuf/stubs/substitute.cc
      - protobuf/google/protobuf/stubs/time.cc
      - protobuf/google/protobuf/text_format.cc
      - protobuf/google/protobuf/timestamp.pb.cc
      - protobuf/google/protobuf/type.pb.cc
      - protobuf/google/protobuf/unknown_field_set.cc
      - protobuf/google/protobuf/util/delimited_message_util.cc
      - protobuf/google/protobuf/util/field_comparator.cc
      - protobuf/google/protobuf/util/field_mask_util.cc
      - protobuf/google/protobuf/util/internal/datapiece.cc
      - protobuf/google/protobuf/util/internal/default_value_objectwriter.cc
      - protobuf/google/protobuf/util/internal/error_listener.cc
      - protobuf/google/protobuf/util/internal/field_mask_utility.cc
      - protobuf/google/protobuf/util/internal/json_escaping.cc
      - protobuf/google/protobuf/util/internal/json_objectwriter.cc
      - protobuf/google/protobuf/util/internal/json_stream_parser.cc
      - protobuf/google/protobuf/util/internal/object_writer.cc
      - protobuf/google/protobuf/util/internal/proto_writer.cc
      - protobuf/google/protobuf/util/internal/protostream_objectsource.cc
      - protobuf/google/protobuf/util/internal/protostream_objectwriter.cc
      - protobuf/google/protobuf/util/internal/type_info.cc
      - protobuf/google/protobuf/util/internal/utility.cc
      - protobuf/google/protobuf/util/json_util.cc
      - protobuf/google/protobuf/util/message_differencer.cc
      - protobuf/google/protobuf/util/time_util.cc
      - protobuf/google/protobuf/util/type_resolver_util.cc
      - protobuf/google/protobuf/wire_format.cc
      - protobuf/google/protobuf/wire_format_lite.cc
      - protobuf/google/protobuf/wrappers.pb.cc
    settings:
      GCC_WARN_64_TO_32_BIT_CONVERSION: NO
      OTHER_CFLAGS: $(inherited) -DHAVE_PTHREAD=1 -Wno-comma -Wno-unreachable-code
