buildscript {
    ext.kotlin_version = '2.1.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.8.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
    configurations.classpath {
        resolutionStrategy.activateDependencyLocking()
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.google.protobuf' &&
                    ('protobuf-java'.equals(details.requested.name) || 'protobuf-java-util'.equals(details.requested.name))) {
                details.useVersion '3.25.5'
            } else if (details.requested.group == 'commons-io') {
                details.useVersion '2.14.0'
            } else if (details.requested.group == 'io.netty') {
                details.useVersion '4.1.138.Final'
            } else if (details.requested.group == 'junit' && details.requested.name == 'junit') {
                details.useVersion '4.13.2'
            }
        }
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    configurations.configureEach {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.google.protobuf' &&
                    ('protobuf-java'.equals(details.requested.name) || 'protobuf-java-util'.equals(details.requested.name))) {
                details.useVersion '3.25.5'
            } else if (details.requested.group == 'commons-io') {
                details.useVersion '2.14.0'
            } else if (details.requested.group == 'io.netty') {
                details.useVersion '4.1.138.Final'
            } else if (details.requested.group == 'junit' && details.requested.name == 'junit') {
                details.useVersion '4.13.2'
            }
        }
    }
    dependencyLocking {
        lockAllConfigurations()
    }
}

subprojects {
    afterEvaluate {
        if (getPlugins().hasPlugin('android') ||
                getPlugins().hasPlugin('android-library')) {
            configure(android.lintOptions) {
                abortOnError false
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
