// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ibc_core_client.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ibc_5fcore_5fclient_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ibc_5fcore_5fclient_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ibc_5fcore_5fclient_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ibc_5fcore_5fclient_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ibc_5fcore_5fclient_2eproto;
namespace ibc {
namespace core {
namespace client {
namespace v1 {
class Height;
struct HeightDefaultTypeInternal;
extern HeightDefaultTypeInternal _Height_default_instance_;
}  // namespace v1
}  // namespace client
}  // namespace core
}  // namespace ibc
PROTOBUF_NAMESPACE_OPEN
template<> ::ibc::core::client::v1::Height* Arena::CreateMaybeMessage<::ibc::core::client::v1::Height>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ibc {
namespace core {
namespace client {
namespace v1 {

// ===================================================================

class Height final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ibc.core.client.v1.Height) */ {
 public:
  inline Height() : Height(nullptr) {}
  ~Height() override;
  explicit constexpr Height(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Height(const Height& from);
  Height(Height&& from) noexcept
    : Height() {
    *this = ::std::move(from);
  }

  inline Height& operator=(const Height& from) {
    CopyFrom(from);
    return *this;
  }
  inline Height& operator=(Height&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Height& default_instance() {
    return *internal_default_instance();
  }
  static inline const Height* internal_default_instance() {
    return reinterpret_cast<const Height*>(
               &_Height_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Height& a, Height& b) {
    a.Swap(&b);
  }
  inline void Swap(Height* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Height* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Height* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Height>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Height& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Height& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Height* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ibc.core.client.v1.Height";
  }
  protected:
  explicit Height(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRevisionNumberFieldNumber = 1,
    kRevisionHeightFieldNumber = 2,
  };
  // uint64 revision_number = 1;
  void clear_revision_number();
  uint64_t revision_number() const;
  void set_revision_number(uint64_t value);
  private:
  uint64_t _internal_revision_number() const;
  void _internal_set_revision_number(uint64_t value);
  public:

  // uint64 revision_height = 2;
  void clear_revision_height();
  uint64_t revision_height() const;
  void set_revision_height(uint64_t value);
  private:
  uint64_t _internal_revision_height() const;
  void _internal_set_revision_height(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:ibc.core.client.v1.Height)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint64_t revision_number_;
  uint64_t revision_height_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ibc_5fcore_5fclient_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Height

// uint64 revision_number = 1;
inline void Height::clear_revision_number() {
  revision_number_ = uint64_t{0u};
}
inline uint64_t Height::_internal_revision_number() const {
  return revision_number_;
}
inline uint64_t Height::revision_number() const {
  // @@protoc_insertion_point(field_get:ibc.core.client.v1.Height.revision_number)
  return _internal_revision_number();
}
inline void Height::_internal_set_revision_number(uint64_t value) {
  
  revision_number_ = value;
}
inline void Height::set_revision_number(uint64_t value) {
  _internal_set_revision_number(value);
  // @@protoc_insertion_point(field_set:ibc.core.client.v1.Height.revision_number)
}

// uint64 revision_height = 2;
inline void Height::clear_revision_height() {
  revision_height_ = uint64_t{0u};
}
inline uint64_t Height::_internal_revision_height() const {
  return revision_height_;
}
inline uint64_t Height::revision_height() const {
  // @@protoc_insertion_point(field_get:ibc.core.client.v1.Height.revision_height)
  return _internal_revision_height();
}
inline void Height::_internal_set_revision_height(uint64_t value) {
  
  revision_height_ = value;
}
inline void Height::set_revision_height(uint64_t value) {
  _internal_set_revision_height(value);
  // @@protoc_insertion_point(field_set:ibc.core.client.v1.Height.revision_height)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace client
}  // namespace core
}  // namespace ibc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ibc_5fcore_5fclient_2eproto
