name: flutter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.4
  path: ^1.9.1
  # path: ^1.8.0

dev_dependencies:
  ffigen: ^19.0.0
  lints: ^5.0.0
  test: ^1.24.0
