// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ethereum.proto

package com.wallet.crypto.trustapp.proto;

public final class Ethereum {
  private Ethereum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Ethereum.Proto.SigningInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Chain identifier (256-bit number)
     * </pre>
     *
     * <code>bytes chain_id = 1;</code>
     */
    com.google.protobuf.ByteString getChainId();

    /**
     * <pre>
     * Nonce (256-bit number)
     * </pre>
     *
     * <code>bytes nonce = 2;</code>
     */
    com.google.protobuf.ByteString getNonce();

    /**
     * <pre>
     * Gas price (256-bit number)
     * </pre>
     *
     * <code>bytes gas_price = 3;</code>
     */
    com.google.protobuf.ByteString getGasPrice();

    /**
     * <pre>
     * Gas limit (256-bit number)
     * </pre>
     *
     * <code>bytes gas_limit = 4;</code>
     */
    com.google.protobuf.ByteString getGasLimit();

    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 5;</code>
     */
    java.lang.String getToAddress();
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 5;</code>
     */
    com.google.protobuf.ByteString
        getToAddressBytes();

    /**
     * <pre>
     * Amount to send in wei (256-bit numner)
     * </pre>
     *
     * <code>bytes amount = 6;</code>
     */
    com.google.protobuf.ByteString getAmount();

    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>bytes payload = 7;</code>
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 8;</code>
     */
    com.google.protobuf.ByteString getPrivateKey();
  }
  /**
   * <pre>
   * Input data necessary to create a signed transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Ethereum.Proto.SigningInput}
   */
  public  static final class SigningInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Ethereum.Proto.SigningInput)
      SigningInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningInput.newBuilder() to construct.
    private SigningInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningInput() {
      chainId_ = com.google.protobuf.ByteString.EMPTY;
      nonce_ = com.google.protobuf.ByteString.EMPTY;
      gasPrice_ = com.google.protobuf.ByteString.EMPTY;
      gasLimit_ = com.google.protobuf.ByteString.EMPTY;
      toAddress_ = "";
      amount_ = com.google.protobuf.ByteString.EMPTY;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              chainId_ = input.readBytes();
              break;
            }
            case 18: {

              nonce_ = input.readBytes();
              break;
            }
            case 26: {

              gasPrice_ = input.readBytes();
              break;
            }
            case 34: {

              gasLimit_ = input.readBytes();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              toAddress_ = s;
              break;
            }
            case 50: {

              amount_ = input.readBytes();
              break;
            }
            case 58: {

              payload_ = input.readBytes();
              break;
            }
            case 66: {

              privateKey_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wallet.crypto.trustapp.proto.Ethereum.internal_static_TW_Ethereum_Proto_SigningInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wallet.crypto.trustapp.proto.Ethereum.internal_static_TW_Ethereum_Proto_SigningInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wallet.crypto.trustapp.proto.Ethereum.SigningInput.class, com.wallet.crypto.trustapp.proto.Ethereum.SigningInput.Builder.class);
    }

    public static final int CHAIN_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString chainId_;
    /**
     * <pre>
     * Chain identifier (256-bit number)
     * </pre>
     *
     * <code>bytes chain_id = 1;</code>
     */
    public com.google.protobuf.ByteString getChainId() {
      return chainId_;
    }

    public static final int NONCE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString nonce_;
    /**
     * <pre>
     * Nonce (256-bit number)
     * </pre>
     *
     * <code>bytes nonce = 2;</code>
     */
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }

    public static final int GAS_PRICE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString gasPrice_;
    /**
     * <pre>
     * Gas price (256-bit number)
     * </pre>
     *
     * <code>bytes gas_price = 3;</code>
     */
    public com.google.protobuf.ByteString getGasPrice() {
      return gasPrice_;
    }

    public static final int GAS_LIMIT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString gasLimit_;
    /**
     * <pre>
     * Gas limit (256-bit number)
     * </pre>
     *
     * <code>bytes gas_limit = 4;</code>
     */
    public com.google.protobuf.ByteString getGasLimit() {
      return gasLimit_;
    }

    public static final int TO_ADDRESS_FIELD_NUMBER = 5;
    private volatile java.lang.Object toAddress_;
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 5;</code>
     */
    public java.lang.String getToAddress() {
      java.lang.Object ref = toAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 5;</code>
     */
    public com.google.protobuf.ByteString
        getToAddressBytes() {
      java.lang.Object ref = toAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString amount_;
    /**
     * <pre>
     * Amount to send in wei (256-bit numner)
     * </pre>
     *
     * <code>bytes amount = 6;</code>
     */
    public com.google.protobuf.ByteString getAmount() {
      return amount_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString payload_;
    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>bytes payload = 7;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 8;</code>
     */
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!chainId_.isEmpty()) {
        output.writeBytes(1, chainId_);
      }
      if (!nonce_.isEmpty()) {
        output.writeBytes(2, nonce_);
      }
      if (!gasPrice_.isEmpty()) {
        output.writeBytes(3, gasPrice_);
      }
      if (!gasLimit_.isEmpty()) {
        output.writeBytes(4, gasLimit_);
      }
      if (!getToAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, toAddress_);
      }
      if (!amount_.isEmpty()) {
        output.writeBytes(6, amount_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(7, payload_);
      }
      if (!privateKey_.isEmpty()) {
        output.writeBytes(8, privateKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!chainId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, chainId_);
      }
      if (!nonce_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, nonce_);
      }
      if (!gasPrice_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, gasPrice_);
      }
      if (!gasLimit_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, gasLimit_);
      }
      if (!getToAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, toAddress_);
      }
      if (!amount_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, amount_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, payload_);
      }
      if (!privateKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, privateKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wallet.crypto.trustapp.proto.Ethereum.SigningInput)) {
        return super.equals(obj);
      }
      com.wallet.crypto.trustapp.proto.Ethereum.SigningInput other = (com.wallet.crypto.trustapp.proto.Ethereum.SigningInput) obj;

      boolean result = true;
      result = result && getChainId()
          .equals(other.getChainId());
      result = result && getNonce()
          .equals(other.getNonce());
      result = result && getGasPrice()
          .equals(other.getGasPrice());
      result = result && getGasLimit()
          .equals(other.getGasLimit());
      result = result && getToAddress()
          .equals(other.getToAddress());
      result = result && getAmount()
          .equals(other.getAmount());
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && getPrivateKey()
          .equals(other.getPrivateKey());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHAIN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChainId().hashCode();
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + getNonce().hashCode();
      hash = (37 * hash) + GAS_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getGasPrice().hashCode();
      hash = (37 * hash) + GAS_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getGasLimit().hashCode();
      hash = (37 * hash) + TO_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getToAddress().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (37 * hash) + PRIVATE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wallet.crypto.trustapp.proto.Ethereum.SigningInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Input data necessary to create a signed transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Ethereum.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Ethereum.Proto.SigningInput)
        com.wallet.crypto.trustapp.proto.Ethereum.SigningInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wallet.crypto.trustapp.proto.Ethereum.internal_static_TW_Ethereum_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wallet.crypto.trustapp.proto.Ethereum.internal_static_TW_Ethereum_Proto_SigningInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wallet.crypto.trustapp.proto.Ethereum.SigningInput.class, com.wallet.crypto.trustapp.proto.Ethereum.SigningInput.Builder.class);
      }

      // Construct using com.wallet.crypto.trustapp.proto.Ethereum.SigningInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        chainId_ = com.google.protobuf.ByteString.EMPTY;

        nonce_ = com.google.protobuf.ByteString.EMPTY;

        gasPrice_ = com.google.protobuf.ByteString.EMPTY;

        gasLimit_ = com.google.protobuf.ByteString.EMPTY;

        toAddress_ = "";

        amount_ = com.google.protobuf.ByteString.EMPTY;

        payload_ = com.google.protobuf.ByteString.EMPTY;

        privateKey_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wallet.crypto.trustapp.proto.Ethereum.internal_static_TW_Ethereum_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      public com.wallet.crypto.trustapp.proto.Ethereum.SigningInput getDefaultInstanceForType() {
        return com.wallet.crypto.trustapp.proto.Ethereum.SigningInput.getDefaultInstance();
      }

      @java.lang.Override
      public com.wallet.crypto.trustapp.proto.Ethereum.SigningInput build() {
        com.wallet.crypto.trustapp.proto.Ethereum.SigningInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wallet.crypto.trustapp.proto.Ethereum.SigningInput buildPartial() {
        com.wallet.crypto.trustapp.proto.Ethereum.SigningInput result = new com.wallet.crypto.trustapp.proto.Ethereum.SigningInput(this);
        result.chainId_ = chainId_;
        result.nonce_ = nonce_;
        result.gasPrice_ = gasPrice_;
        result.gasLimit_ = gasLimit_;
        result.toAddress_ = toAddress_;
        result.amount_ = amount_;
        result.payload_ = payload_;
        result.privateKey_ = privateKey_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wallet.crypto.trustapp.proto.Ethereum.SigningInput) {
          return mergeFrom((com.wallet.crypto.trustapp.proto.Ethereum.SigningInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wallet.crypto.trustapp.proto.Ethereum.SigningInput other) {
        if (other == com.wallet.crypto.trustapp.proto.Ethereum.SigningInput.getDefaultInstance()) return this;
        if (other.getChainId() != com.google.protobuf.ByteString.EMPTY) {
          setChainId(other.getChainId());
        }
        if (other.getNonce() != com.google.protobuf.ByteString.EMPTY) {
          setNonce(other.getNonce());
        }
        if (other.getGasPrice() != com.google.protobuf.ByteString.EMPTY) {
          setGasPrice(other.getGasPrice());
        }
        if (other.getGasLimit() != com.google.protobuf.ByteString.EMPTY) {
          setGasLimit(other.getGasLimit());
        }
        if (!other.getToAddress().isEmpty()) {
          toAddress_ = other.toAddress_;
          onChanged();
        }
        if (other.getAmount() != com.google.protobuf.ByteString.EMPTY) {
          setAmount(other.getAmount());
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        if (other.getPrivateKey() != com.google.protobuf.ByteString.EMPTY) {
          setPrivateKey(other.getPrivateKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wallet.crypto.trustapp.proto.Ethereum.SigningInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wallet.crypto.trustapp.proto.Ethereum.SigningInput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString chainId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Chain identifier (256-bit number)
       * </pre>
       *
       * <code>bytes chain_id = 1;</code>
       */
      public com.google.protobuf.ByteString getChainId() {
        return chainId_;
      }
      /**
       * <pre>
       * Chain identifier (256-bit number)
       * </pre>
       *
       * <code>bytes chain_id = 1;</code>
       */
      public Builder setChainId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Chain identifier (256-bit number)
       * </pre>
       *
       * <code>bytes chain_id = 1;</code>
       */
      public Builder clearChainId() {
        
        chainId_ = getDefaultInstance().getChainId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString nonce_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Nonce (256-bit number)
       * </pre>
       *
       * <code>bytes nonce = 2;</code>
       */
      public com.google.protobuf.ByteString getNonce() {
        return nonce_;
      }
      /**
       * <pre>
       * Nonce (256-bit number)
       * </pre>
       *
       * <code>bytes nonce = 2;</code>
       */
      public Builder setNonce(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nonce (256-bit number)
       * </pre>
       *
       * <code>bytes nonce = 2;</code>
       */
      public Builder clearNonce() {
        
        nonce_ = getDefaultInstance().getNonce();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString gasPrice_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Gas price (256-bit number)
       * </pre>
       *
       * <code>bytes gas_price = 3;</code>
       */
      public com.google.protobuf.ByteString getGasPrice() {
        return gasPrice_;
      }
      /**
       * <pre>
       * Gas price (256-bit number)
       * </pre>
       *
       * <code>bytes gas_price = 3;</code>
       */
      public Builder setGasPrice(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gasPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Gas price (256-bit number)
       * </pre>
       *
       * <code>bytes gas_price = 3;</code>
       */
      public Builder clearGasPrice() {
        
        gasPrice_ = getDefaultInstance().getGasPrice();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString gasLimit_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Gas limit (256-bit number)
       * </pre>
       *
       * <code>bytes gas_limit = 4;</code>
       */
      public com.google.protobuf.ByteString getGasLimit() {
        return gasLimit_;
      }
      /**
       * <pre>
       * Gas limit (256-bit number)
       * </pre>
       *
       * <code>bytes gas_limit = 4;</code>
       */
      public Builder setGasLimit(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gasLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Gas limit (256-bit number)
       * </pre>
       *
       * <code>bytes gas_limit = 4;</code>
       */
      public Builder clearGasLimit() {
        
        gasLimit_ = getDefaultInstance().getGasLimit();
        onChanged();
        return this;
      }

      private java.lang.Object toAddress_ = "";
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 5;</code>
       */
      public java.lang.String getToAddress() {
        java.lang.Object ref = toAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 5;</code>
       */
      public com.google.protobuf.ByteString
          getToAddressBytes() {
        java.lang.Object ref = toAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 5;</code>
       */
      public Builder setToAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 5;</code>
       */
      public Builder clearToAddress() {
        
        toAddress_ = getDefaultInstance().getToAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 5;</code>
       */
      public Builder setToAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toAddress_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString amount_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Amount to send in wei (256-bit numner)
       * </pre>
       *
       * <code>bytes amount = 6;</code>
       */
      public com.google.protobuf.ByteString getAmount() {
        return amount_;
      }
      /**
       * <pre>
       * Amount to send in wei (256-bit numner)
       * </pre>
       *
       * <code>bytes amount = 6;</code>
       */
      public Builder setAmount(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Amount to send in wei (256-bit numner)
       * </pre>
       *
       * <code>bytes amount = 6;</code>
       */
      public Builder clearAmount() {
        
        amount_ = getDefaultInstance().getAmount();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Optional payload
       * </pre>
       *
       * <code>bytes payload = 7;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       * Optional payload
       * </pre>
       *
       * <code>bytes payload = 7;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Optional payload
       * </pre>
       *
       * <code>bytes payload = 7;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 8;</code>
       */
      public com.google.protobuf.ByteString getPrivateKey() {
        return privateKey_;
      }
      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 8;</code>
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 8;</code>
       */
      public Builder clearPrivateKey() {
        
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Ethereum.Proto.SigningInput)
    }

    // @@protoc_insertion_point(class_scope:TW.Ethereum.Proto.SigningInput)
    private static final com.wallet.crypto.trustapp.proto.Ethereum.SigningInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wallet.crypto.trustapp.proto.Ethereum.SigningInput();
    }

    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningInput>
        PARSER = new com.google.protobuf.AbstractParser<SigningInput>() {
      @java.lang.Override
      public SigningInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningInput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wallet.crypto.trustapp.proto.Ethereum.SigningInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Ethereum.Proto.SigningOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     */
    com.google.protobuf.ByteString getEncoded();

    /**
     * <code>bytes v = 2;</code>
     */
    com.google.protobuf.ByteString getV();

    /**
     * <code>bytes r = 3;</code>
     */
    com.google.protobuf.ByteString getR();

    /**
     * <code>bytes s = 4;</code>
     */
    com.google.protobuf.ByteString getS();
  }
  /**
   * <pre>
   * Transaction signing output.
   * </pre>
   *
   * Protobuf type {@code TW.Ethereum.Proto.SigningOutput}
   */
  public  static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Ethereum.Proto.SigningOutput)
      SigningOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningOutput.newBuilder() to construct.
    private SigningOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningOutput() {
      encoded_ = com.google.protobuf.ByteString.EMPTY;
      v_ = com.google.protobuf.ByteString.EMPTY;
      r_ = com.google.protobuf.ByteString.EMPTY;
      s_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              encoded_ = input.readBytes();
              break;
            }
            case 18: {

              v_ = input.readBytes();
              break;
            }
            case 26: {

              r_ = input.readBytes();
              break;
            }
            case 34: {

              s_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wallet.crypto.trustapp.proto.Ethereum.internal_static_TW_Ethereum_Proto_SigningOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wallet.crypto.trustapp.proto.Ethereum.internal_static_TW_Ethereum_Proto_SigningOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput.class, com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput.Builder.class);
    }

    public static final int ENCODED_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encoded_;
    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     */
    public com.google.protobuf.ByteString getEncoded() {
      return encoded_;
    }

    public static final int V_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString v_;
    /**
     * <code>bytes v = 2;</code>
     */
    public com.google.protobuf.ByteString getV() {
      return v_;
    }

    public static final int R_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString r_;
    /**
     * <code>bytes r = 3;</code>
     */
    public com.google.protobuf.ByteString getR() {
      return r_;
    }

    public static final int S_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString s_;
    /**
     * <code>bytes s = 4;</code>
     */
    public com.google.protobuf.ByteString getS() {
      return s_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!encoded_.isEmpty()) {
        output.writeBytes(1, encoded_);
      }
      if (!v_.isEmpty()) {
        output.writeBytes(2, v_);
      }
      if (!r_.isEmpty()) {
        output.writeBytes(3, r_);
      }
      if (!s_.isEmpty()) {
        output.writeBytes(4, s_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!encoded_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, encoded_);
      }
      if (!v_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, v_);
      }
      if (!r_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, r_);
      }
      if (!s_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, s_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput)) {
        return super.equals(obj);
      }
      com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput other = (com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput) obj;

      boolean result = true;
      result = result && getEncoded()
          .equals(other.getEncoded());
      result = result && getV()
          .equals(other.getV());
      result = result && getR()
          .equals(other.getR());
      result = result && getS()
          .equals(other.getS());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENCODED_FIELD_NUMBER;
      hash = (53 * hash) + getEncoded().hashCode();
      hash = (37 * hash) + V_FIELD_NUMBER;
      hash = (53 * hash) + getV().hashCode();
      hash = (37 * hash) + R_FIELD_NUMBER;
      hash = (53 * hash) + getR().hashCode();
      hash = (37 * hash) + S_FIELD_NUMBER;
      hash = (53 * hash) + getS().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Transaction signing output.
     * </pre>
     *
     * Protobuf type {@code TW.Ethereum.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Ethereum.Proto.SigningOutput)
        com.wallet.crypto.trustapp.proto.Ethereum.SigningOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wallet.crypto.trustapp.proto.Ethereum.internal_static_TW_Ethereum_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wallet.crypto.trustapp.proto.Ethereum.internal_static_TW_Ethereum_Proto_SigningOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput.class, com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput.Builder.class);
      }

      // Construct using com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        encoded_ = com.google.protobuf.ByteString.EMPTY;

        v_ = com.google.protobuf.ByteString.EMPTY;

        r_ = com.google.protobuf.ByteString.EMPTY;

        s_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wallet.crypto.trustapp.proto.Ethereum.internal_static_TW_Ethereum_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      public com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput getDefaultInstanceForType() {
        return com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput.getDefaultInstance();
      }

      @java.lang.Override
      public com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput build() {
        com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput buildPartial() {
        com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput result = new com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput(this);
        result.encoded_ = encoded_;
        result.v_ = v_;
        result.r_ = r_;
        result.s_ = s_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput) {
          return mergeFrom((com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput other) {
        if (other == com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput.getDefaultInstance()) return this;
        if (other.getEncoded() != com.google.protobuf.ByteString.EMPTY) {
          setEncoded(other.getEncoded());
        }
        if (other.getV() != com.google.protobuf.ByteString.EMPTY) {
          setV(other.getV());
        }
        if (other.getR() != com.google.protobuf.ByteString.EMPTY) {
          setR(other.getR());
        }
        if (other.getS() != com.google.protobuf.ByteString.EMPTY) {
          setS(other.getS());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString encoded_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       */
      public com.google.protobuf.ByteString getEncoded() {
        return encoded_;
      }
      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       */
      public Builder setEncoded(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encoded_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       */
      public Builder clearEncoded() {
        
        encoded_ = getDefaultInstance().getEncoded();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString v_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes v = 2;</code>
       */
      public com.google.protobuf.ByteString getV() {
        return v_;
      }
      /**
       * <code>bytes v = 2;</code>
       */
      public Builder setV(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        v_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes v = 2;</code>
       */
      public Builder clearV() {
        
        v_ = getDefaultInstance().getV();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString r_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes r = 3;</code>
       */
      public com.google.protobuf.ByteString getR() {
        return r_;
      }
      /**
       * <code>bytes r = 3;</code>
       */
      public Builder setR(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        r_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes r = 3;</code>
       */
      public Builder clearR() {
        
        r_ = getDefaultInstance().getR();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString s_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes s = 4;</code>
       */
      public com.google.protobuf.ByteString getS() {
        return s_;
      }
      /**
       * <code>bytes s = 4;</code>
       */
      public Builder setS(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        s_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes s = 4;</code>
       */
      public Builder clearS() {
        
        s_ = getDefaultInstance().getS();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Ethereum.Proto.SigningOutput)
    }

    // @@protoc_insertion_point(class_scope:TW.Ethereum.Proto.SigningOutput)
    private static final com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput();
    }

    public static com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningOutput>
        PARSER = new com.google.protobuf.AbstractParser<SigningOutput>() {
      @java.lang.Override
      public SigningOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningOutput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningOutput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wallet.crypto.trustapp.proto.Ethereum.SigningOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Ethereum_Proto_SigningInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Ethereum_Proto_SigningInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Ethereum_Proto_SigningOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Ethereum_Proto_SigningOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Ethereum.proto\022\021TW.Ethereum.Proto\"\237\001\n\014" +
      "SigningInput\022\020\n\010chain_id\030\001 \001(\014\022\r\n\005nonce\030" +
      "\002 \001(\014\022\021\n\tgas_price\030\003 \001(\014\022\021\n\tgas_limit\030\004 " +
      "\001(\014\022\022\n\nto_address\030\005 \001(\t\022\016\n\006amount\030\006 \001(\014\022" +
      "\017\n\007payload\030\007 \001(\014\022\023\n\013private_key\030\010 \001(\014\"A\n" +
      "\rSigningOutput\022\017\n\007encoded\030\001 \001(\014\022\t\n\001v\030\002 \001" +
      "(\014\022\t\n\001r\030\003 \001(\014\022\t\n\001s\030\004 \001(\014B\"\n com.wallet.c" +
      "rypto.trustapp.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TW_Ethereum_Proto_SigningInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TW_Ethereum_Proto_SigningInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Ethereum_Proto_SigningInput_descriptor,
        new java.lang.String[] { "ChainId", "Nonce", "GasPrice", "GasLimit", "ToAddress", "Amount", "Payload", "PrivateKey", });
    internal_static_TW_Ethereum_Proto_SigningOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TW_Ethereum_Proto_SigningOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Ethereum_Proto_SigningOutput_descriptor,
        new java.lang.String[] { "Encoded", "V", "R", "S", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
