install! 'cocoapods', :deterministic_uuids => false, :share_schemes_for_development_pods => true

def dev_pod
  pod 'WalletCore', :path => '../..'
end

target 'Example' do
  platform :ios, '13.0'
  use_frameworks! :linkage => :static
  dev_pod
  target 'ExampleTests' do
      inherit! :complete
  end
end

target 'ExampleMac' do
  platform :osx, '10.12'
  use_frameworks! :linkage => :dynamic
  dev_pod
end
