opt_out_usage
default_platform(:ios)

platform :ios do
  desc "create full xcframeworks"
  lane :xcframework do
    swift_protobuf_xcframework
    core_xcframework
  end

  desc "create wallet core xcframework"
  lane :core_xcframework do
    create_xcframework(
      workspace: 'TrustWalletCore.xcworkspace',
      scheme: 'WalletCore',
      destinations: ['iOS'],
      xcframework_output_directory: 'build',
      enable_bitcode: false
    )
  end

  desc "create swift protobuf xcframework"
  lane :swift_protobuf_xcframework do
    create_xcframework(
      workspace: 'TrustWalletCore.xcworkspace',
      scheme: 'WalletCoreSwiftProtobuf',
      destinations: ['iOS'],
      xcframework_output_directory: 'build',
      enable_bitcode: false
    )
  end
end
