default_platform(:ios)

platform :ios do
  desc "create xcframework"
  lane :core_xcframework do
    create_xcframework(
      workspace: 'TrustWalletCore.xcworkspace',
      scheme: 'WalletCore',
      destinations: ['iOS', 'macOS'],
      xcframework_output_directory: 'build'
    )
  end
  desc "create swift protobuf xcframework"
  lane :swift_protobuf_xcframework do
    create_xcframework(
      workspace: 'TrustWalletCore.xcworkspace',
      scheme: 'SwiftProtobuf',
      destinations: ['iOS', 'macOS'],
      xcframework_output_directory: 'build'
    )
  end
end
