#!/bin/bash
#
# This script builds the Android release package.

set -e

source $(dirname $0)/library
version=$(wc_read_version)

pushd android
./gradlew assembleRelease
cp trustwalletcore/build/outputs/aar/trustwalletcore-release.aar ../build/trustwalletcore.aar
popd

echo "Now upload build/trustwalletcore.aar to https://github.com/TrustWallet/trust-wallet-core/releases/tag/$version"

echo "Building docs..."
tools/kotlin-doc

echo "Now upload Kotlin docs from build/kdoc.zip to whatever place it needs to be"
