#!/bin/bash
#
# This script installs dependencies needed for android build.

CLANG_VERSION=7.0.1
CMAKE_VERSION=3.13.4
PROTOBUF_VERSION=3.7.0

# Install the basics
#apt-get update && apt-get install curl && apt-get install -y curl python-software-properties build-essential xz-utils libreadline-dev
#
## Make latest NodeJS available
#curl -sL https://deb.nodesource.com/setup_10.x | bash -
#
## Install all required packages
#apt-get install -y \
#    autoconf \
#    git \
#    libcurl4-openssl-dev \
#    libicu-dev \
#    libssl-dev \
#    libtool \
#    ninja-build \
#    nodejs \
#    pkg-config \
#    unzip
#
## Install ruby 2.6
# Install chruby (https://github.com/postmodern/chruby#readme)
mkdir -p $HOME/src
cd $HOME/src
wget -O chruby-0.3.9.tar.gz https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
tar -xzvf chruby-0.3.9.tar.gz
cd chruby-0.3.9/
PREFIX=$HOME/.chruby make install

# Add the source lines to your ~/.bashrc or ~/.zshrc
echo "source ~/.chruby/share/chruby/chruby.sh" >> ~/.bashrc
echo "source ~/.chruby/share/chruby/auto.sh" >> ~/.bashrc

# Then set whatever Ruby version you want as default
echo "ruby-2.6.3" > ~/.ruby-version
## Install clang
export CLANG_VERSION=$CLANG_VERSION
wget "http://releases.llvm.org/$CLANG_VERSION/clang+llvm-$CLANG_VERSION-x86_64-linux-gnu-ubuntu-16.04.tar.xz" -o clang.tar.xz \
    && tar -xJf clang.tar.xz --directory /usr --strip-components=1 \
    && rm -rf clang.tar.xz

# Install Boost
wget -c 'http://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.bz2/download'
tar xf download
cd boost_1_66_0
./bootstrap.sh
./b2 install

# Install CMake
export CMAKE_VERSION=$CMAKE_VERSION
wget "https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION.tar.gz" \
    && tar xvf cmake-$CMAKE_VERSION.tar.gz \
    && cd cmake-$CMAKE_VERSION \
    && ./bootstrap --system-curl \
    && make \
    && make install \
    && cd .. \
    && rm -rf cmake*
cmake --version
#
## Clean Up
#apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
#
#tools/install-dependencies
