#!/bin/bash
#
# This script builds the Docker image(s)

docker build -t trustwallet/wallet-core:latest ./docker/wallet-core
docker build -t trustwallet/wallet-core-run:latest ./docker/wallet-core-run
