#!/bin/bash
#
# This script generates all protobuf files using the embedded version of
# Protobuf. It is important that the version used to generate the files is the
# same version being linked.
#
# You only need to run this if you change a .proto file or update the Protobuf
# submodule.
#

set -e

ROOT="$PWD"
PREFIX="${PREFIX:-$ROOT/build/local}"
PATH="$PREFIX/bin":$PATH
PROTOC="$PREFIX/bin/protoc"

# Clean
rm -rf swift/Sources/Generated
rm -rf jni/java
rm -rf jni/cpp/generated

# Generate coins info from coins.json
codegen/bin/coins

# Generate interface code
codegen/bin/codegen

# Generate Java, C++ and Swift Protobuf files
if [ -x "$(command -v protoc-gen-swift)" ]; then
    "$PROTOC" -I=$PREFIX/include -I=src/proto --cpp_out=src/proto --java_out=jni/java --swift_out=swift/Sources/Generated --swift_opt=Visibility=Public src/proto/*.proto
else
    "$PROTOC" -I=$PREFIX/include -I=src/proto --cpp_out=src/proto --java_out=jni/java src/proto/*.proto
fi

# Generate internal Protobuf files
"$PROTOC" -I=$PREFIX/include -I=src/Tron/Protobuf --cpp_out=src/Tron/Protobuf src/Tron/Protobuf/*.proto
"$PROTOC" -I=$PREFIX/include -I=src/Zilliqa/Protobuf --cpp_out=src/Zilliqa/Protobuf src/Zilliqa/Protobuf/*.proto

# Generate Proto interface file
pushd protobuf-plugin
cmake -H. -Bbuild
make -Cbuild
popd
"$PROTOC" -I=$PREFIX/include -I=src/proto --plugin=protobuf-plugin/build/protoc-gen-c-typedef --c-typedef_out include/TrustWalletCore src/proto/*.proto
"$PROTOC" -I=$PREFIX/include -I=src/proto --plugin=protobuf-plugin/build/protoc-gen-swift-typealias --swift-typealias_out swift/Sources/Generated src/proto/*.proto

# Generate Xcode project
if [ -x "$(command -v xcodegen)" ]; then
    pushd swift
    xcodegen
    pod install
    popd
else
    echo -e "\nWARNING: Skipped generating Xcode project because the xcodegen tool is not installed."
fi
