#!/bin/bash
#
# This script uploads android build to repositories defined in maven-push.gradle
# It also builds and uploads Kotlin docs

set -e

source $(dirname $0)/library
version=$(wc_read_version  $1)

if [[ `uname` == "Darwin" ]]; then
    export BOOST_ROOT=$(brew --prefix boost)
fi

echo "Building $version"

#export ANDROID_HOME="$HOME/Library/Android/sdk"
pushd android
#./gradlew clean build assembleRelease publish -Pversion="$version"
./gradlew clean build assembleRelease -Pversion="$version"

echo "Android build generated"
popd # android

find android -iname '*.aar'
ls -l android/wallet-core/build/outputs/aar/*.aar
