#!/bin/bash

set -e

# build-essential clang-14 libc++-dev libc++abi-dev ruby-full cmake
sudo apt-get update && sudo apt-get install ninja-build lcov clang-tidy-17 libboost-all-dev rustc --fix-missing

mkdir -p build/local
wget https://apt.llvm.org/llvm.sh -P build/local
chmod +x build/local/llvm.sh
sudo build/local/llvm.sh 17
