#!/bin/bash

set -e

emsdk_version=4.0.22

git clone https://github.com/emscripten-core/emsdk.git

cd emsdk


./emsdk install $emsdk_version && ./emsdk activate $emsdk_version

curl -fSsOL https://github.com/emscripten-ports/boost/releases/download/boost-1.83.0/boost-headers-1.83.0.zip
unzip boost-headers-1.83.0.zip -d upstream/emscripten/system/include
