#!/bin/bash

set -e

# build-essential clang-15 libc++-dev libc++abi-dev ruby-full cmake
sudo apt-get update && sudo apt-get install ninja-build lcov llvm-15 clang-15 clang-tidy-15 libboost-all-dev rustc --fix-missing
