#!/bin/bash

set -e

ROOT="$PWD"
PREFIX="${PREFIX:-$ROOT/build/local}"
echo "PREFIX: $PREFIX"

# Setup up folders
export PATH="$PREFIX/bin":$PATH
export LDFLAGS="-L$PREFIX/lib"
export LT_SYS_LIBRARY_PATH="$PREFIX/lib"
export DYLD_LIBRARY_PATH="$PREFIX/lib"
export LD_LIBRARY_PATH="$PREFIX/lib"
export LD_RUN_PATH="$PREFIX/lib"

# Download Check
export CHECK_VERSION=0.12.0
CHECK_DIR="$ROOT/build/local/src/check"
mkdir -p "$CHECK_DIR"
cd "$CHECK_DIR"
if [ ! -f check-$CHECK_VERSION.tar.gz ]; then
    curl -fSsOL https://github.com/libcheck/check/releases/download/0.12.0/check-$CHECK_VERSION.tar.gz
fi
tar xzf check-$CHECK_VERSION.tar.gz

# Build Check
cd check-$CHECK_VERSION
./configure --prefix="$PREFIX"
make -j4
make install
make clean

if [[ -x "$(command -v swift)" && `uname` == "Darwin" ]]; then
    # Download Swift Protobuf sources
    export SWIFT_PROTOBUF_VERSION=1.9.0
    SWIFT_PROTOBUF_DIR="$ROOT/build/local/src/swift-protobuf"
    mkdir -p "$SWIFT_PROTOBUF_DIR"
    cd "$SWIFT_PROTOBUF_DIR"
    if [ ! -f $SWIFT_PROTOBUF_VERSION.tar.gz ]; then
        curl -fSsOL https://github.com/apple/swift-protobuf/archive/$SWIFT_PROTOBUF_VERSION.tar.gz
    fi
    tar xzf $SWIFT_PROTOBUF_VERSION.tar.gz

    # Build Swift Protobuf
    cd swift-protobuf-$SWIFT_PROTOBUF_VERSION
    swift build --static-swift-stdlib -c release
    cp -f "$SWIFT_PROTOBUF_DIR/swift-protobuf-$SWIFT_PROTOBUF_VERSION/.build/release/protoc-gen-swift" "$PREFIX/bin" | true
    $PREFIX/bin/protoc-gen-swift --version
fi

# Protobuf plugins
cd "$ROOT/protobuf-plugin"
cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=$PREFIX
make -Cbuild -j12
make -Cbuild install
rm -rf build

cd "$ROOT"
