#!/bin/bash

set -e

if [[ `uname` == "Darwin" ]]; then
  rustup update
  rustup toolchain install nightly
  rustup default nightly
  rustup toolchain install nightly-x86_64-apple-darwin
  rustup toolchain install nightly-aarch64-apple-darwin
  rustup component add rust-src --toolchain nightly-aarch64-apple-darwin
  rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
fi
rustup target add aarch64-linux-android aarch64-apple-darwin x86_64-apple-darwin x86_64-linux-android armv7-linux-androideabi i686-linux-android x86_64-apple-ios aarch64-apple-ios-sim aarch64-apple-ios wasm32-unknown-emscripten
cargo install cbindgen
