#!/bin/bash

set -e

if [[ `uname` == "Darwin" || "$1" == "dev" ]]; then
  rustup update
  rustup toolchain install nightly
  rustup default nightly
  rustup toolchain install nightly-x86_64-apple-darwin --force-non-host
  rustup toolchain install nightly-aarch64-apple-darwin --force-non-host
  rustup component add rust-src --toolchain nightly-aarch64-apple-darwin
  rustup component add rust-src --toolchain nightly-x86_64-apple-darwin
fi

# Android
rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android
# iOS
rustup target add aarch64-apple-darwin x86_64-apple-darwin
# macOS
rustup target add x86_64-apple-ios aarch64-apple-ios-sim aarch64-apple-ios
# Wasm
rustup target add wasm32-unknown-emscripten

cargo install cbindgen --locked

if [[ "$1" == "dev" ]]; then
  rustup component add llvm-tools-preview clippy rustfmt
  cargo install cargo-llvm-cov --locked
  cargo install cargo-nextest --locked
fi
