#!/bin/bash
#
# This script builds dynamic WalletCore and WalletCoreSwiftProtobuf xcframework for SPM and CocoaPods
#

set -e

echo "Building Docc..."
tools/ios-doc

echo "Building xcframework..."
pushd swift
fastlane ios xcframework
popd
