#!/bin/bash
#
# This script builds a xcframework for iOS devices / simulators and Mac Catalyst.
#

set -e

FRAMEWORK=TrustWalletCore
BUILD_FOLDER=build/ios-frameworks

function init() {
    pushd swift
    xcodegen && pod install
    popd

    rm -rf $BUILD_FOLDER/*.xcarchive
    rm -rf $BUILD_FOLDER/$FRAMEWORK.xcframework
}

function build() {
    xcodebuild archive -workspace swift/$FRAMEWORK.xcworkspace \
                -scheme $FRAMEWORK \
                -destination "$1" \
                -archivePath $BUILD_FOLDER/"$2".xcarchive \
                SKIP_INSTALL=NO clean
}

function buildDevices() {
    build "generic/platform=iOS" "ios-dev"
}

function buildSimulators() {
    build "platform=iOS Simulator,name=iPhone 11,OS=13.3" "ios-sim"
}

function buildCatalyst() {
    build "platform=macOS,arch=x86_64,variant=Mac Catalyst" "mac-catalyst"
}

function buildXCFramework() {
    xcodebuild -create-xcframework -output $BUILD_FOLDER/$FRAMEWORK.xcframework \
               -framework $BUILD_FOLDER/mac-catalyst.xcarchive/Products/Library/Frameworks/$FRAMEWORK.framework \
               -framework $BUILD_FOLDER/ios-dev.xcarchive/Products/Library/Frameworks/$FRAMEWORK.framework \
               -framework $BUILD_FOLDER/ios-sim.xcarchive/Products/Library/Frameworks/$FRAMEWORK.framework
}

function main() {
    init
    buildDevices
    buildSimulators
    buildCatalyst
    buildXCFramework
}

main
