#!/bin/bash
#
# This script runs the iOS tests.

set -e
set -o pipefail

pushd swift

xcodegen && pod install
xcodebuild -workspace TrustWalletCore.xcworkspace \
	-scheme WalletCore \
	-sdk iphonesimulator \
	-destination "platform=iOS Simulator,name=iPhone 14" \
	test | xcbeautify

popd
