#!/bin/bash
#
# This script publishes JavaScript module to npm.

set -e

pushd js

echo "Installing..."
npm install

echo "Building & packaging..."
npm run build

echo "Testing..."
npm test

echo "Publishing binary..."
npm run binary:publish

popd
