#!/bin/bash

set -e

source $(dirname $0)/library
version=$(wc_read_version)

echo "Building $version"

export ANDROID_HOME="$HOME/Library/Android/sdk"

pushd kotlin
./gradlew :TrustWalletCore:generateFiles
./gradlew :TrustWalletCore:assemble :TrustWalletCore:publish -Pversion="$version"
popd

echo "Kotlin build uploaded"
