#!/bin/bash
#
# Builds Kotlin artifacts for release
#
# Usage: kotlin-release <version>
#   version - version to build (required)

set -e

source "$(dirname "$0")/library"
version=$(wc_read_version "$1")

echo "Building Kotlin $version"

export ANDROID_HOME="$HOME/Library/Android/sdk"
BOOST_ROOT=$(brew --prefix boost)
export BOOST_ROOT

pushd kotlin
./gradlew :wallet-core-kotlin:generateProtos
./gradlew :wallet-core-kotlin:assemble -Pversion="$version"
popd

echo "Kotlin build completed"
