#!/bin/bash
#
# This script uploads android build to bintray.

set -e

version=`git describe --long --tags | cut -f 1 -d "-"`
snapshot=$1
export ANDROID_HOME="$HOME/Library/Android/sdk"
pushd android

./gradlew clean build assembleRelease publish -Pversion="$version"

echo "Android build uploaded"
