#!/bin/bash
#
# This script uploads android build to bintray.

set -e

version=`git describe --long --tags | cut -f 1 -d "-"`
snapshot=$1

pushd android

if [ "$snapshot" = true ]; then
  version=`git rev-parse --short HEAD`"-SNAPSHOT"
  ./gradlew clean build artifactoryPublish -Pversion="$version"
else
  ./gradlew clean build bintrayUpload -Pversion="$version"
fi

echo "Abroid build uploaded"