#!/bin/bash
#
# This script generate a build folder with pvs studio enabled and run an analyze
# If you are on MacOS set CC/CXX to clang/clang++ from llvm brew

base_dir=$(
  cd $(dirname $0)
  pwd
)
src_dir=${base_dir}/..

mkdir -p "${src_dir}"/build_pvs_studio
cd "${src_dir}"/build_pvs_studio

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  cmake -GNinja -DTW_ENABLE_PVS_STUDIO=ON -DTW_IDE_VSCODE=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ../
elif [[ "$OSTYPE" == "darwin"* ]]; then
  cmake -GNinja -DTW_ENABLE_PVS_STUDIO=ON -DTW_IDE_VSCODE=ON -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ ../
fi

ninja TrustWalletCore.analyze

cd -
