#!/bin/bash

rustup target add aarch64-linux-android i686-linux-android x86_64-apple-ios aarch64-apple-ios-sim aarch64-apple-ios wasm32-unknown-emscripten
cargo install cargo-lipo

TARGET_NAME="libwalletcore_crypto_bindgen.a"
cd bindgen/rust
echo "Generating Native targets"
CARGO_TARGET_DIR=../../build/local cargo build --release
CARGO_TARGET_DIR=../../build/local cargo build --target wasm32-unknown-emscripten --release
if [[ $OSTYPE == 'darwin'* ]]; then
  echo "Generating Android targets"
  CARGO_TARGET_DIR=../../build/local cargo build --target aarch64-linux-android --release
  CARGO_TARGET_DIR=../../build/local cargo build --target i686-linux-android --release
  echo "Generating iOS targets"
  CARGO_TARGET_DIR=../../build/local cargo lipo --release
  CARGO_TARGET_DIR=../../build/local cargo build --target aarch64-apple-ios-sim --release
fi
cbindgen --crate walletcore-crypto-bindgen --output ../../src/rust/bindgen/WalletCoreCryptoBindgen.h
cd -
mv build/local/release/${TARGET_NAME} build/local/lib/
