#!/bin/bash
#
# Run Rust tests. Options:
# - General tests
#   ./tools/rust-test
# - Generating coverage info:
#   ./tools/rust-test coverage
# - Generating HTML coverage info:
#   ./tools/rust-test html
#
# See `tools/check-coverage` to parse the coverage report.

# Fail if any commands fails
set -e

pushd rust

# Generate HTML report if requested
if [[ "$1" == "coverage" ]]; then
    cargo llvm-cov --lcov --output-path coverage.info
elif [[ "$1" == "html" ]]; then
    cargo llvm-cov test --html
else
    cargo test --all
fi

popd
