#!/bin/bash

#
# This script processes captured test code coverage information of the Rust part,
# generates HTML report (if html argument is given),
# and compares current value to previously saved value (stored in coverage.stats).
#
# To generate coverage info:
# - install cargo-llvm-cov binary
#   cargo install cargo-llvm-cov
# - run unit tests ang generate coverage info (slow). Optionally generate report in HTML format:
#   ./tools/rust-coverage html

# Fail if any commands fails
set -e

pushd rust

# Generate HTML report if requested
if [[ "$1" == "html" ]]; then
    cargo llvm-cov test --html
    exit 0
else
    cargo llvm-cov --lcov --output-path coverage.info
fi

# TODO move the following instructions to a separate script.
lcov --summary coverage.info

echo
current=$(<coverage.stats)
new=$(lcov --summary coverage.info | awk '/lines.*:/{sub("%", "", $2);print $2}')

if (( $(echo "$current > $new" | bc -l) )); then
    echo "Code coverage drops to ${new}% (current is ${current}%)"
    exit -1
else
    echo "Update code coverage: ${current}% -> ${new}%"
    echo -n $new > coverage.stats
    # commit to master
fi

popd
