#!/bin/bash
#
# This script builds the sample applications, on Android

set -e

pushd samples/android
echo "Building Android sample app:"`pwd`
./gradlew assembleDebug
echo "Building Android sample app: done"
popd
