#!/bin/bash
#
# This script builds the sample applications.

set -e

pushd samples/cpp
echo "Building CPP sample app:"`pwd`
cmake . -DWALLET_CORE=../../
make
echo "Building CPP sample app: done"
popd

#pushd samples/osx/cocoapods
#echo "Building iOS sample app:"`pwd`
#pod install
#echo "Building iOS sample app: done"
#popd

#pushd samples/android
#echo "Building Android sample app:"`pwd`
#
#echo "Building Android sample app: done"
#popd

pushd samples/go
echo "Building GO sample app:"`pwd`
go build -o main
echo "Building GO sample app: done"
popd
