#!/bin/bash
#
# This script builds the sample applications, on iOS

set -e

pushd samples/osx/cocoapods
echo "Building OSX sample app:"`pwd`
pod repo update
pod install
echo "Building OSX sample app: done"
popd
