#!/bin/bash
#
# This script builds the sample applications, on Linux

set -e

pushd samples/cpp
echo "Building CPP sample app:"`pwd`
cmake . -DWALLET_CORE=../../
make
echo "Building CPP sample app: done"
popd

pushd samples/go
echo "Building GO sample app:"`pwd`
go build -o main
echo "Building GO sample app: done"
popd
