#!/usr/bin/env bash
#
# This script runs all the tests on all supported platforms.

set -e

cmake -H. -Bbuild
make -Cbuild -j12 tests

export CK_TIMEOUT_MULTIPLIER=4

build/tests/tests tests

tools/ios-test
tools/android-test
