#!/usr/bin/env bash
#
# This script runs all the tests on all supported platforms.

set -e

cmake -H. -Bbuild
make -Cbuild -j12 tests TrezorCryptoTests

export CK_TIMEOUT_MULTIPLIER=4
build/trezor-crypto/crypto/tests/TrezorCryptoTests

build/tests/tests tests

tools/ios-test
tools/android-test
