#!/bin/bash

set -e

base_dir=$(cd `dirname $0`; pwd)
src_dir=${base_dir}/..

if [[ -z ${EMSDK} ]]; then
    source ${src_dir}/emsdk/emsdk_env.sh
fi

build_folder=${src_dir}/wasm-build
boost_dir=${EMSDK}/upstream/emscripten/system/include
pushd ${src_dir}

cp cmake/Wasm.cmake CMakeLists.txt

# cmake
emcmake cmake -Bwasm-build -DBoost_INCLUDE_DIR=${boost_dir}

# make
emmake make -Cwasm-build

popd
