#!/bin/bash

set -e

base_dir=$(cd `dirname $0`; pwd)
src_dir=${base_dir}/..
package_json=${src_dir}/wasm/package.json

version=$(cat ${package_json} | jq '.version')
npm_version=\"$(npm view @trustwallet/wallet-core version)\"

if [[ ${version} != ${npm_version} ]]; then
  echo true
else
  echo false
fi
