// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: Nano.proto

package nano

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common "tw/protos/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Input data necessary to create a signed transaction.
type SigningInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The secret private key used for signing (32 bytes).
	PrivateKey []byte `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// Optional parent block hash
	ParentBlock []byte `protobuf:"bytes,2,opt,name=parent_block,json=parentBlock,proto3" json:"parent_block,omitempty"`
	// Receive/Send reference
	//
	// Types that are valid to be assigned to LinkOneof:
	//
	//	*SigningInput_LinkBlock
	//	*SigningInput_LinkRecipient
	LinkOneof isSigningInput_LinkOneof `protobuf_oneof:"link_oneof"`
	// Representative address
	Representative string `protobuf:"bytes,5,opt,name=representative,proto3" json:"representative,omitempty"`
	// Account balance (128-bit unsigned integer, as a string)
	Balance string `protobuf:"bytes,6,opt,name=balance,proto3" json:"balance,omitempty"`
	// Work
	Work string `protobuf:"bytes,7,opt,name=work,proto3" json:"work,omitempty"`
	// Pulic key used for building preImage (32 bytes).
	PublicKey     []byte `protobuf:"bytes,8,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_Nano_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_Nano_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_Nano_proto_rawDescGZIP(), []int{0}
}

func (x *SigningInput) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *SigningInput) GetParentBlock() []byte {
	if x != nil {
		return x.ParentBlock
	}
	return nil
}

func (x *SigningInput) GetLinkOneof() isSigningInput_LinkOneof {
	if x != nil {
		return x.LinkOneof
	}
	return nil
}

func (x *SigningInput) GetLinkBlock() []byte {
	if x != nil {
		if x, ok := x.LinkOneof.(*SigningInput_LinkBlock); ok {
			return x.LinkBlock
		}
	}
	return nil
}

func (x *SigningInput) GetLinkRecipient() string {
	if x != nil {
		if x, ok := x.LinkOneof.(*SigningInput_LinkRecipient); ok {
			return x.LinkRecipient
		}
	}
	return ""
}

func (x *SigningInput) GetRepresentative() string {
	if x != nil {
		return x.Representative
	}
	return ""
}

func (x *SigningInput) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *SigningInput) GetWork() string {
	if x != nil {
		return x.Work
	}
	return ""
}

func (x *SigningInput) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type isSigningInput_LinkOneof interface {
	isSigningInput_LinkOneof()
}

type SigningInput_LinkBlock struct {
	// Hash of a block to receive from
	LinkBlock []byte `protobuf:"bytes,3,opt,name=link_block,json=linkBlock,proto3,oneof"`
}

type SigningInput_LinkRecipient struct {
	// Recipient address to send coins to
	LinkRecipient string `protobuf:"bytes,4,opt,name=link_recipient,json=linkRecipient,proto3,oneof"`
}

func (*SigningInput_LinkBlock) isSigningInput_LinkOneof() {}

func (*SigningInput_LinkRecipient) isSigningInput_LinkOneof() {}

// Result containing the signed and encoded transaction.
type SigningOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signature
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Block hash
	BlockHash []byte `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// JSON representation of the block
	Json string `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	// error code, 0 is ok, other codes will be treated as errors
	Error common.SigningError `protobuf:"varint,4,opt,name=error,proto3,enum=TW.Common.Proto.SigningError" json:"error,omitempty"`
	// error code description
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_Nano_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_Nano_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_Nano_proto_rawDescGZIP(), []int{1}
}

func (x *SigningOutput) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SigningOutput) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *SigningOutput) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *SigningOutput) GetError() common.SigningError {
	if x != nil {
		return x.Error
	}
	return common.SigningError(0)
}

func (x *SigningOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_Nano_proto protoreflect.FileDescriptor

const file_Nano_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"Nano.proto\x12\rTW.Nano.Proto\x1a\fCommon.proto\"\x9f\x02\n" +
	"\fSigningInput\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\fR\n" +
	"privateKey\x12!\n" +
	"\fparent_block\x18\x02 \x01(\fR\vparentBlock\x12\x1f\n" +
	"\n" +
	"link_block\x18\x03 \x01(\fH\x00R\tlinkBlock\x12'\n" +
	"\x0elink_recipient\x18\x04 \x01(\tH\x00R\rlinkRecipient\x12&\n" +
	"\x0erepresentative\x18\x05 \x01(\tR\x0erepresentative\x12\x18\n" +
	"\abalance\x18\x06 \x01(\tR\abalance\x12\x12\n" +
	"\x04work\x18\a \x01(\tR\x04work\x12\x1d\n" +
	"\n" +
	"public_key\x18\b \x01(\fR\tpublicKeyB\f\n" +
	"\n" +
	"link_oneof\"\xba\x01\n" +
	"\rSigningOutput\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12\x12\n" +
	"\x04json\x18\x03 \x01(\tR\x04json\x123\n" +
	"\x05error\x18\x04 \x01(\x0e2\x1d.TW.Common.Proto.SigningErrorR\x05error\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessageB\x17\n" +
	"\x15wallet.core.jni.protob\x06proto3"

var (
	file_Nano_proto_rawDescOnce sync.Once
	file_Nano_proto_rawDescData []byte
)

func file_Nano_proto_rawDescGZIP() []byte {
	file_Nano_proto_rawDescOnce.Do(func() {
		file_Nano_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Nano_proto_rawDesc), len(file_Nano_proto_rawDesc)))
	})
	return file_Nano_proto_rawDescData
}

var file_Nano_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Nano_proto_goTypes = []any{
	(*SigningInput)(nil),     // 0: TW.Nano.Proto.SigningInput
	(*SigningOutput)(nil),    // 1: TW.Nano.Proto.SigningOutput
	(common.SigningError)(0), // 2: TW.Common.Proto.SigningError
}
var file_Nano_proto_depIdxs = []int32{
	2, // 0: TW.Nano.Proto.SigningOutput.error:type_name -> TW.Common.Proto.SigningError
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Nano_proto_init() }
func file_Nano_proto_init() {
	if File_Nano_proto != nil {
		return
	}
	file_Nano_proto_msgTypes[0].OneofWrappers = []any{
		(*SigningInput_LinkBlock)(nil),
		(*SigningInput_LinkRecipient)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Nano_proto_rawDesc), len(file_Nano_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Nano_proto_goTypes,
		DependencyIndexes: file_Nano_proto_depIdxs,
		MessageInfos:      file_Nano_proto_msgTypes,
	}.Build()
	File_Nano_proto = out.File
	file_Nano_proto_goTypes = nil
	file_Nano_proto_depIdxs = nil
}
