if(TW_ENABLE_CLANG_TIDY)
    find_program(CLANGTIDY clang-tidy)
    if(CLANGTIDY)
        set(CMAKE_CXX_CLANG_TIDY ${CLANGTIDY} -extra-arg=-Wno-unknown-warning-option)
        message("Clang-Tidy finished setting up.")
    else()
        message(SEND_ERROR "Clang-Tidy requested but executable not found.")
    endif()
endif()
