[package]
name = "tw_komodo"
version = "0.1.0"
edition = "2021"

[dependencies]
tw_bitcoin = { path = "../../chains/tw_bitcoin" }
tw_coin_entry = { path = "../../tw_coin_entry" }
tw_keypair = { path = "../../tw_keypair" }
tw_proto = { path = "../../tw_proto" }
tw_utxo = { path = "../../frameworks/tw_utxo" }
tw_zcash = { path = "../../chains/tw_zcash" }
