name: JNI Linux Release

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  jni-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          tools/install-sys-dependencies-linux
          tools/install-rust-dependencies

      - name: Cache internal dependencies
        id: internal_cache
        uses: actions/cache@v3
        with:
          path: build/local
          key: ${{ runner.os }}-internal-${{ hashFiles('tools/install-sys-dependencies-linux') }}-${{ hashFiles('tools/install-dependencies') }}
      - name: Install internal dependencies
        run: |
          tools/install-dependencies
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
        if: steps.internal_cache.outputs.cache-hit != 'true'

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            rust

      - name: Code generation
        run: |
          tools/generate-files native
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++

      - name: CMake (Java, Kotlin)
        run: |
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DTW_COMPILE_JAVA=ON -DTW_COMPILE_KOTLIN=ON -GNinja
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++

      - name: Build WalletCore JNI
        run: |
          ninja -Cbuild
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
